openapi: '3.0.2'
info:
  title: 'Metadata Service'
  description: 'Used to provide and update metadata, such as table & column description, stored in either neo4j or apache atlas.'
  version: '1.1.7'

components:
  schemas:
    ColumnDescription:
      type: object
      properties:
        description:
          type: string
          description: 'A description of the column'
          example: '(for a user_id for example) Used to uniquely identify a user'
    PopularTables:
      type: object
      properties:
        popular_tables:
          type: array
          items:
            type: object
            properties:
              database:
                description: Database name
                type: string
              cluster:
                description: Cluster name
                type: string
              schema:
                description: Schema name
                type: string
              table_name:
                description: Table name
                type: string
              table_description:
                description: Table description
                type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: 'A simple description of what went wrong'
          example: 'An Exception encountered while processing your request'
    EmptyResponse:
      type: object
      properties: {}
